### ISSUE TITLE
jsonld-0.3 breaks rdflib tests

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib-jsonld#30]
rdflib by default doesn't install rdflib-jsonld. so if you run rdflib's tests it will magically skip them in case jsonld can't be found.

I just ran the tests locally (Mac OS X 10.9.5, rdflib 4.2.1-dev, with `./run_tests.py`) in a venv where jsonld 0.3 is installed and it shows the following errors:

```
======================================================================
FAIL: http://code.google.com/p/rdflib/issues/detail?id=5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/joern/coding/git/rdflib/rdflib/test/test_finalnewline.py", line 30, in testFinalNewline
    assert len(failed)==0, "No final newline for formats: '%s'" % failed
AssertionError: No final newline for formats: 'set(['json-ld'])'

======================================================================
FAIL: test.test_roundtrip.test_cases(('nt', 'json-ld', 'test/nt/keywords-04.nt'),)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/joern/coding/git/rdflib/rdflib/test/test_roundtrip.py", line 62, in roundtrip
    assert rdflib.compare.isomorphic(g1, g2)
AssertionError

======================================================================
FAIL: test.test_roundtrip.test_cases(('nt', 'json-ld', 'test/nt/lists-03.nt'),)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/joern/coding/git/rdflib/rdflib/test/test_roundtrip.py", line 62, in roundtrip
    assert rdflib.compare.isomorphic(g1, g2)
AssertionError

======================================================================
FAIL: test.test_roundtrip.test_cases(('nt', 'json-ld', 'test/nt/lists-04.nt'),)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/joern/coding/git/rdflib/rdflib/test/test_roundtrip.py", line 62, in roundtrip
    assert rdflib.compare.isomorphic(g1, g2)
AssertionError

----------------------------------------------------------------------
Ran 2387 tests in 37.948s

FAILED (SKIP=97, failures=4)
```

maybe someone could have a look?

once this is fixed, i'm tempted to update travis so it also installs jsonld and tests the rdflib integration...

**Comment by niklasl** [comment]
I'll make some time to sort this out.

If we make `rdflib` depend on this package (which I like), we should make `rdflib-jsonld`:s dependency on `rdflib` optional, so that we don't have a circular dependency (see rdflib/RDFLib#391 which was resolved when SPARQLWrapper put `rdflib` in `requires` instead of `install_requires` IIRC).

**Comment by niklasl** [comment]
(Btw, I'd like to note that RDFLib/rdflib#436 is al blocker for having proper support for datasets in JSON-LD.)

**Comment by joernhees** [comment]
well, i was actually just surprised that if `rdflib-jsonld` is installed the `rdflib` tests failed... so my intent here was first to make sure that the integration works by auto-installing it in the test environment (not as a default dependency of rdflib). But maybe you're right and it's time to revive RDFLib/rdflib#391...

**Comment by joernhees** [comment]
is RDFLib/rdflib#436 a blocker for the tests i mentioned above? otherwise i'd opt to keep the issues separated
